apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iffp47yie-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iffp47yie-python 
  name: iffp47yie-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iffp47yie-python 
